-- =============================================================================
-- Sprint 37 — Loan & Credit Management Module (Gestão de Empréstimos)
-- Migration: 20260324000005_lending_module.sql
-- Author: AI Architect (TheAdvisor DevOS)
-- Date: 2026-03-24
--
-- Creates:
--   1. ENUMs        — loan_status, interest_type
--   2. TABLE        — loans          (contracts / contratos)
--   3. TABLE        — loan_installments (parcelas)
--   4. RLS          — strict business-scoped policies for both tables
--   5. RPC          — generate_loan_installments(p_loan_id UUID)
--                     Auto-inserts N installment rows using PMT (compound)
--                     or simple-interest formula, 30 days apart.
-- =============================================================================

-- =============================================================================
-- SECTION 1: ENUMs
-- =============================================================================

DO $$ BEGIN
    CREATE TYPE public.loan_status AS ENUM (
        'active',
        'paid',
        'defaulted',
        'cancelled'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE public.interest_type AS ENUM (
        'simple',
        'compound'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE public.installment_status AS ENUM (
        'pending',
        'partial',
        'paid',
        'overdue'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- =============================================================================
-- SECTION 2: TABLES
-- =============================================================================

-- ----------------------------------------------------------------------------
-- TABLE: loans (Contratos de Empréstimo)
-- One row per loan contract. Anchored to a business and optionally a CRM customer.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loans (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Tenant isolation: every loan is owned by exactly one business.
    business_id         UUID            NOT NULL
                            REFERENCES public.businesses(id) ON DELETE CASCADE,

    -- Optional link to CRM customer. NULL = anonymous / external borrower.
    customer_id         UUID
                            REFERENCES public.customers(id) ON DELETE SET NULL,

    -- Financial terms
    principal_amount    NUMERIC(15, 2)  NOT NULL
                            CHECK (principal_amount > 0),
    interest_rate       NUMERIC(8, 6)   NOT NULL
                            CHECK (interest_rate >= 0),           -- decimal fraction: 0.02 = 2 %/period
    interest_type       public.interest_type NOT NULL,
    total_installments  INT             NOT NULL
                            CHECK (total_installments > 0),

    -- Contract lifecycle
    status              public.loan_status NOT NULL DEFAULT 'active',
    start_date          DATE            NOT NULL,                  -- reference for first due date
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.loans IS
    'One row per loan contract. All repayment maths pivot on principal_amount, interest_rate, interest_type. '
    'Call generate_loan_installments(id) after INSERT to auto-create parcelas.';

COMMENT ON COLUMN public.loans.interest_rate IS
    'Decimal fraction per period. Example: 0.015 = 1.5 % per month. '
    'Compound interest uses this as the monthly rate in the PMT formula. '
    'Simple interest spreads P×(1 + r×n) evenly over n periods.';

COMMENT ON COLUMN public.loans.customer_id IS
    'Optional FK to public.customers. NULL means the borrower has no CRM profile.';

-- ----------------------------------------------------------------------------
-- TABLE: loan_installments (Parcelas)
-- One row per scheduled repayment. Generated by the RPC; never inserted directly.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.loan_installments (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    loan_id             UUID            NOT NULL
                            REFERENCES public.loans(id) ON DELETE CASCADE,

    installment_number  INT             NOT NULL
                            CHECK (installment_number > 0),
    due_date            DATE            NOT NULL,

    -- Expected repayment amount (PMT or simple slice) — set once at generation time.
    expected_amount     NUMERIC(15, 2)  NOT NULL
                            CHECK (expected_amount > 0),

    -- Actual amount received. Defaults to 0, supports partial payments (baixa dinâmica).
    -- When paid_amount >= expected_amount the row is considered fully paid.
    paid_amount         NUMERIC(15, 2)  NOT NULL DEFAULT 0
                            CHECK (paid_amount >= 0),

    status              public.installment_status NOT NULL DEFAULT 'pending',

    -- Set by the application when status transitions to 'paid'
    paid_at             TIMESTAMPTZ,

    CONSTRAINT uq_loan_installment UNIQUE (loan_id, installment_number)
);

COMMENT ON TABLE public.loan_installments IS
    'Scheduled repayment rows (parcelas). Auto-generated via generate_loan_installments(). '
    'Do not INSERT manually — use the RPC to ensure consistency with the loan terms.';

COMMENT ON COLUMN public.loan_installments.paid_amount IS
    'Supports baixa dinâmica (partial payments). '
    'Application logic should set status=''partial'' when 0 < paid_amount < expected_amount, '
    'and status=''paid'' + paid_at=now() when paid_amount >= expected_amount.';

-- =============================================================================
-- SECTION 3: INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_loans_business_id
    ON public.loans (business_id);

CREATE INDEX IF NOT EXISTS idx_loans_customer_id
    ON public.loans (customer_id);

CREATE INDEX IF NOT EXISTS idx_loans_status
    ON public.loans (business_id, status);

CREATE INDEX IF NOT EXISTS idx_loan_installments_loan_id
    ON public.loan_installments (loan_id);

CREATE INDEX IF NOT EXISTS idx_loan_installments_due_date
    ON public.loan_installments (loan_id, due_date);

CREATE INDEX IF NOT EXISTS idx_loan_installments_status
    ON public.loan_installments (loan_id, status);

-- =============================================================================
-- SECTION 4: ROW LEVEL SECURITY
-- =============================================================================
-- Philosophy: Default DENY. Users may only touch loans/installments that belong
-- to a business they are a member of (owner OR employee via business_members).
-- We reuse get_my_business_ids() — the SECURITY DEFINER helper defined in
-- 20260323000009_businesses_rls_employee_access.sql.
-- =============================================================================

ALTER TABLE public.loans             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loan_installments ENABLE ROW LEVEL SECURITY;

-- ── loans ─────────────────────────────────────────────────────────────────────

-- SELECT: all authorized business members can read contracts
CREATE POLICY loans_select_business_member
    ON public.loans
    FOR SELECT
    USING (business_id IN (SELECT public.get_my_business_ids()));

-- INSERT: any business member can open a new loan contract
CREATE POLICY loans_insert_business_member
    ON public.loans
    FOR INSERT
    WITH CHECK (business_id IN (SELECT public.get_my_business_ids()));

-- UPDATE: any business member can update (e.g., change status). For stricter
-- controls (owner/manager only) add a role check here like governance_schema does.
CREATE POLICY loans_update_business_member
    ON public.loans
    FOR UPDATE
    USING  (business_id IN (SELECT public.get_my_business_ids()))
    WITH CHECK (business_id IN (SELECT public.get_my_business_ids()));

-- ── loan_installments ─────────────────────────────────────────────────────────
-- Policies join back to loans to inherit the same business_id guard.

CREATE POLICY loan_installments_select_business_member
    ON public.loan_installments
    FOR SELECT
    USING (
        loan_id IN (
            SELECT id FROM public.loans
            WHERE  business_id IN (SELECT public.get_my_business_ids())
        )
    );

CREATE POLICY loan_installments_insert_business_member
    ON public.loan_installments
    FOR INSERT
    WITH CHECK (
        loan_id IN (
            SELECT id FROM public.loans
            WHERE  business_id IN (SELECT public.get_my_business_ids())
        )
    );

CREATE POLICY loan_installments_update_business_member
    ON public.loan_installments
    FOR UPDATE
    USING (
        loan_id IN (
            SELECT id FROM public.loans
            WHERE  business_id IN (SELECT public.get_my_business_ids())
        )
    )
    WITH CHECK (
        loan_id IN (
            SELECT id FROM public.loans
            WHERE  business_id IN (SELECT public.get_my_business_ids())
        )
    );

-- =============================================================================
-- SECTION 5: GRANT STATEMENTS
-- =============================================================================

REVOKE ALL ON public.loans             FROM anon, authenticated;
REVOKE ALL ON public.loan_installments FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE ON public.loans             TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.loan_installments TO authenticated;

-- =============================================================================
-- SECTION 6: RPC — generate_loan_installments
-- =============================================================================
-- Input:  p_loan_id UUID — must already exist in public.loans
-- Output: INT — number of installment rows inserted
--
-- Formula selection:
--   SIMPLE INTEREST
--     Total payable = P × (1 + r × n)
--     Each installment = ROUND(total_payable / n, 2)
--
--   COMPOUND INTEREST (French/Price amortisation — equal PMT)
--     When r > 0:
--       PMT = P × r × (1 + r)^n / ((1 + r)^n - 1)
--     When r = 0 (zero-interest plan):
--       PMT = P / n
--
-- Due dates: start_date + (installment_number × 30) days
--   e.g. start_date=2026-04-01, n=3 → due 2026-05-01, 2026-06-01, 2026-07-01
-- =============================================================================
CREATE OR REPLACE FUNCTION public.generate_loan_installments(p_loan_id UUID)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_loan              RECORD;
    v_pmt               NUMERIC(15, 2);
    v_power             NUMERIC;          -- (1 + r)^n  used twice in PMT
    v_installment_num   INT;
    v_inserted          INT := 0;
BEGIN
    -- ── 1. Fetch and lock the loan row ────────────────────────────────────────
    SELECT *
    INTO   v_loan
    FROM   public.loans
    WHERE  id = p_loan_id
    FOR UPDATE;                           -- prevent concurrent double-generation

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Loan not found: %', p_loan_id;
    END IF;

    -- ── 2. Guard: do not regenerate if installments already exist ─────────────
    IF EXISTS (
        SELECT 1 FROM public.loan_installments WHERE loan_id = p_loan_id
    ) THEN
        RAISE EXCEPTION
            'Installments already generated for loan %. Delete existing rows first.', p_loan_id;
    END IF;

    -- ── 3. Calculate per-installment payment amount ────────────────────────────
    IF v_loan.interest_type = 'simple' THEN
        -- Simple interest: spread P×(1 + r×n) evenly
        v_pmt := ROUND(
            v_loan.principal_amount * (1 + v_loan.interest_rate * v_loan.total_installments)
            / v_loan.total_installments,
            2
        );

    ELSE
        -- Compound interest (PMT / anuidade / French amortisation)
        IF v_loan.interest_rate = 0 THEN
            -- Zero-rate edge case: simple division
            v_pmt := ROUND(v_loan.principal_amount / v_loan.total_installments, 2);
        ELSE
            v_power := POWER(
                (1 + v_loan.interest_rate)::NUMERIC,
                v_loan.total_installments::NUMERIC
            );
            v_pmt := ROUND(
                v_loan.principal_amount * v_loan.interest_rate * v_power / (v_power - 1),
                2
            );
        END IF;
    END IF;

    -- ── 4. Insert one row per installment ─────────────────────────────────────
    FOR v_installment_num IN 1 .. v_loan.total_installments LOOP
        INSERT INTO public.loan_installments (
            loan_id,
            installment_number,
            due_date,
            expected_amount,
            paid_amount,
            status
        ) VALUES (
            p_loan_id,
            v_installment_num,
            v_loan.start_date + (v_installment_num * 30),    -- 30-day intervals
            v_pmt,
            0,
            'pending'
        );
        v_inserted := v_inserted + 1;
    END LOOP;

    RETURN v_inserted;
END;
$$;

COMMENT ON FUNCTION public.generate_loan_installments(UUID) IS
    'Accepts a loan_id. Calculates the equal periodic payment (PMT for compound, '
    'simple-interest slice for simple type) and inserts loan_installments rows '
    '30 days apart from the loan start_date. Returns the count of rows inserted. '
    'Raises an exception if the loan does not exist or installments already exist.';

-- Grant to authenticated so it can be called as an RPC from the client
GRANT EXECUTE ON FUNCTION public.generate_loan_installments(UUID) TO authenticated;

-- =============================================================================
-- END OF MIGRATION: 20260324000005_lending_module.sql
-- =============================================================================
